some rocky linux config that works

diff --git a/rocky.yaml b/rocky.yaml
--- a/rocky.yaml
+++ b/rocky.yaml
@@ -1,5 +1,5 @@
-#schema
-#https://github.com/lxc/distrobuilder/blob/main/doc/examples/scheme.yaml
+#https://github.com/lxc/lxc-ci/blob/main/images/rockylinux.yaml
+
 image:
   name: rockylinux-k8s
   distribution: rockylinux
@@ -11,114 +11,483 @@ image:
 
 source:
   downloader: rockylinux-http
-  url: https://mirror.netcologne.de/rocky/
-  variant: minimal
-  keys: #gpg --homedir /tmp/distrobuilder/rockylinux-10-x86_64/gpg.2444647378 --keyserver hkps.pool.sks-keyservers.net --recv-keys 0xBFAE243EDEF0530191A226314C360B7022B7FA33
-    - |
-      -----BEGIN PGP PUBLIC KEY BLOCK-----
+  url: https://download.rockylinux.org/pub/rocky/
+  keys:
+  # RPM-GPG-KEY-Rocky-10
+  - |-
+    -----BEGIN PGP PUBLIC KEY BLOCK-----
 
-      mQINBGgq4akBEADFYHb9OX5/hlSJuYezxnzab01PUnec4/WvRdU5QRCySzlSicxd
-      CYRrasQEYnytGBrTMM7fGSDOH9BtVpKfFvOW8yxfBXgkXbBT2p2/PK96qjIistbG
-      GZK5yU5qhHTO4H30MaKvO8u+q3Icdtxc1I2OuGTrWQ0+MAI7dZPmNTqrvBlqks/V
-      D6Uj9SSYpV0n12GdFQZI36+MXuI170vr0qRWaU8cl0Ew3nqU9rOBvnHPzab5UhCy
-      g5+XE7QwRpKKziRxWNc40hU1OpT8yr4hoZdw9LimdA0yc7mniz7cWGPffMrfBQck
-      1TKfLC8WsTSJ32ZPT/GildTIyEOv229ofhfBnY8H+MeD1ccW352yHflvKr9Pfhxt
-      2lQuN7qCFpm5kip13hgKSnBL9M8JRICvjedrY4Q3yOfFZytWIsYsY2KAHe8lLTaR
-      afPtnC8TWkiqR3P+dpaWopnoayuVAVFIK2jzix8PgC+TwYSH+IJcmw1O1WwpDt8q
-      JfAE9Sh9X07mfbGnp0tJGG/+HXuSdwII/GXQeRE0L34DT7XcY3e3tuYCCoSpnvtm
-      VvKpW42TfGfjwRWpW/fia30YHLXSoff26G38E5LfQTjjl95uyQWv3wpDExUrDOez
-      d2hDZ3iJVWRZP3YZ1zgJexwlVoPTbDUe/wPcrFo5Don4YFD54ctUp/O39wARAQAB
-      tDxSZWxlYXNlIEVuZ2luZWVyaW5nIChSb2NreSBMaW51eCAxMCkgPHJlbGVuZ0By
-      b2NreWxpbnV4Lm9yZz6JAlIEEwEIADwWIQT8ImhZwIYL8N25WwhbEGxzb+38hQUC
-      aCrhqQIbDwULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQWxBsc2/t/IWE
-      sA/8CrZAFJwkMo2geIhcWW37XCGfKwUfB42QKkJQYoF2biOQxIcGGYU3AaA4HSfx
-      o3CvutpwTgOQmG4ZfQd920KXMcSLd0actHQ+iJP+NPFv50ks2igv51QdPLQtZKvg
-      A/tlKh4Oc0kgNBxueD5AZv8FJBEPQ7I0J/Ph9Ev1ShJrjnlVpTelNAdTNoNqf0xD
-      LH7J0kyYgqbea+vxQposbc9hnaqRWv7hbAOj8cYbhkvvtG6oyn+AZaJoM00rTAsL
-      cPjZk+HQdyUYB6JSKRZ5J16yn+D0UMwmmTI02dpd5ClFopGD/mT2erOn8hAhvvqF
-      Wr1EZEKH6YwF6PzdZ9KtbGPhRcRzVeO7EOAmZu0jhvkMTjNODYHy4xsueJ+rHf1I
-      M4rDSL579tPLAqYmnW1S3AbrJ0WkJc9KsWwzNRC5r+ftq2eTncfTU7RfGtw9shqR
-      fTkB4NUMfTOtSUrDeWYYEQtCekexoqhaP7gjsUqWNTSPgConOFIwMsT0XOvPPJgS
-      Dc0hnV6ew148jAf2L03hgDctqgsrUW3KB18bpkjUE7zfL1tweSqU3VDEQStxX9h8
-      hG+VGHS7G7F4yYTcZOTlYfDU8ex/HkudPSOfwMnftqVnXqUpnQDKkUUPyxSCVKr8
-      yN2apurNRzlrmWlJ8IuBtYFSSEqJ6sncQ/LrJRQQLTKp7sE=
-      =32Ym
-      -----END PGP PUBLIC KEY BLOCK-----
+    mQINBGgq4akBEADFYHb9OX5/hlSJuYezxnzab01PUnec4/WvRdU5QRCySzlSicxd
+    CYRrasQEYnytGBrTMM7fGSDOH9BtVpKfFvOW8yxfBXgkXbBT2p2/PK96qjIistbG
+    GZK5yU5qhHTO4H30MaKvO8u+q3Icdtxc1I2OuGTrWQ0+MAI7dZPmNTqrvBlqks/V
+    D6Uj9SSYpV0n12GdFQZI36+MXuI170vr0qRWaU8cl0Ew3nqU9rOBvnHPzab5UhCy
+    g5+XE7QwRpKKziRxWNc40hU1OpT8yr4hoZdw9LimdA0yc7mniz7cWGPffMrfBQck
+    1TKfLC8WsTSJ32ZPT/GildTIyEOv229ofhfBnY8H+MeD1ccW352yHflvKr9Pfhxt
+    2lQuN7qCFpm5kip13hgKSnBL9M8JRICvjedrY4Q3yOfFZytWIsYsY2KAHe8lLTaR
+    afPtnC8TWkiqR3P+dpaWopnoayuVAVFIK2jzix8PgC+TwYSH+IJcmw1O1WwpDt8q
+    JfAE9Sh9X07mfbGnp0tJGG/+HXuSdwII/GXQeRE0L34DT7XcY3e3tuYCCoSpnvtm
+    VvKpW42TfGfjwRWpW/fia30YHLXSoff26G38E5LfQTjjl95uyQWv3wpDExUrDOez
+    d2hDZ3iJVWRZP3YZ1zgJexwlVoPTbDUe/wPcrFo5Don4YFD54ctUp/O39wARAQAB
+    tDxSZWxlYXNlIEVuZ2luZWVyaW5nIChSb2NreSBMaW51eCAxMCkgPHJlbGVuZ0By
+    b2NreWxpbnV4Lm9yZz6JAlIEEwEIADwWIQT8ImhZwIYL8N25WwhbEGxzb+38hQUC
+    aCrhqQIbDwULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQWxBsc2/t/IWE
+    sA/8CrZAFJwkMo2geIhcWW37XCGfKwUfB42QKkJQYoF2biOQxIcGGYU3AaA4HSfx
+    o3CvutpwTgOQmG4ZfQd920KXMcSLd0actHQ+iJP+NPFv50ks2igv51QdPLQtZKvg
+    A/tlKh4Oc0kgNBxueD5AZv8FJBEPQ7I0J/Ph9Ev1ShJrjnlVpTelNAdTNoNqf0xD
+    LH7J0kyYgqbea+vxQposbc9hnaqRWv7hbAOj8cYbhkvvtG6oyn+AZaJoM00rTAsL
+    cPjZk+HQdyUYB6JSKRZ5J16yn+D0UMwmmTI02dpd5ClFopGD/mT2erOn8hAhvvqF
+    Wr1EZEKH6YwF6PzdZ9KtbGPhRcRzVeO7EOAmZu0jhvkMTjNODYHy4xsueJ+rHf1I
+    M4rDSL579tPLAqYmnW1S3AbrJ0WkJc9KsWwzNRC5r+ftq2eTncfTU7RfGtw9shqR
+    fTkB4NUMfTOtSUrDeWYYEQtCekexoqhaP7gjsUqWNTSPgConOFIwMsT0XOvPPJgS
+    Dc0hnV6ew148jAf2L03hgDctqgsrUW3KB18bpkjUE7zfL1tweSqU3VDEQStxX9h8
+    hG+VGHS7G7F4yYTcZOTlYfDU8ex/HkudPSOfwMnftqVnXqUpnQDKkUUPyxSCVKr8
+    yN2apurNRzlrmWlJ8IuBtYFSSEqJ6sncQ/LrJRQQLTKp7sE=
+    =32Ym
+    -----END PGP PUBLIC KEY BLOCK-----
+  variant: minimal
 
 targets:
   incus:
     vm:
       size: 26843545600 # 25 GiB in bytes (25 * 1024 * 1024 * 1024)
       filesystem: ext4
+
 files:
-  - generator: fstab         # /etc/fstab file system table
-  - generator: incus-agent
-  - generator: hostname
-    path: /etc/hostname
-  - generator: hosts
-    path: /etc/hosts
-  - generator: dump
-    path: /etc/sysctl.d/99-kubernetes-cri.conf
-    content: |
-      net.bridge.bridge-nf-call-iptables  = 1
-      net.bridge.bridge-nf-call-ip6tables = 1
-      net.ipv4.ip_forward                 = 1
+- name: hostname
+  path: /etc/hostname
+  generator: hostname
+
+- name: hosts
+  path: /etc/hosts
+  generator: hosts
+
+- path: /etc/machine-id
+  generator: dump
+  content: uninitialized
+
+- path: /var/lib/dbus/machine-id
+  generator: remove
+
+
+- name: ifcfg-enp5s0.incus
+  path: /etc/sysconfig/network-scripts/ifcfg-enp5s0
+  generator: template
+  content: |-
+    DEVICE=enp5s0
+    BOOTPROTO=dhcp
+    ONBOOT=yes
+    HOSTNAME={{ container.name }}
+    TYPE=Ethernet
+    MTU=
+    DHCP_HOSTNAME={{ container.name }}
+  types:
+  - vm
+
+- path: /etc/default/grub
+  generator: dump
+  content: |-
+    # Set the recordfail timeout
+    GRUB_RECORDFAIL_TIMEOUT=0
+    # Do not wait on grub prompt
+    GRUB_TIMEOUT=0
+    # Set the default commandline
+    GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} console=tty1 console=ttyS0"
+    # Set the grub console type
+    GRUB_TERMINAL=console
+    # Disable os-prober
+    GRUB_DISABLE_OS_PROBER=true
+  types:
+  - vm
+
+- path: /etc/dracut.conf.d/incus.conf
+  generator: dump
+  content: |-
+    add_drivers+=" virtio_scsi virtio_console sd_mod "
+  types:
+  - vm
+
+- generator: fstab
+  types:
+  - vm
+
+- name: 86-nm-unmanaged.rules
+  path: /etc/udev/rules.d/86-nm-unmanaged.rules
+  generator: dump
+  content: |-
+    ENV{ID_NET_DRIVER}=="veth", ENV{NM_UNMANAGED}="0"
+
+- name: network
+  path: /etc/sysconfig/network
+  generator: dump
+  templated: true
+  content: |-
+    NETWORKING=yes
+    HOSTNAME=LXC_NAME
+
+- name: network.incus
+  path: /etc/sysconfig/network
+  generator: template
+  content: |-
+    NETWORKING=yes
+    HOSTNAME={{ container.name }}
+
+- name: meta-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: network-config
+  generator: cloud-init
+  content: |-
+    {% if config_get("user.network-config", "") == "" %}version: 1
+    config:
+      - type: physical
+        name: {% if instance.type == "virtual-machine" %}enp5s0{% else %}eth0{% endif %}
+        subnets:
+          - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
+            control: auto
+          - type: dhcp6
+            control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
+  variants:
+  - cloud
+
+- name: user-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- name: vendor-data
+  generator: cloud-init
+  variants:
+  - cloud
+
+- generator: incus-agent
+  types:
+  - vm
 
 packages:
-  # 1. Choose the backend package manager engine
-  manager: dnf
-
-  # 2. Update all underlying system packages to the latest release
+  manager: yum
   update: true
-
-  # 3. Explicitly declare core packages to inject
+  cleanup: true
   sets:
-    - action: install
-      packages:
-      # --- Vital System & Boot Utilities ---
-      - kernel
-      - grub2-efi-x64        # Required for UEFI booting
-      - shim-x64             # Required for secure boot chain compatibility
-      - efibootmgr           # Allows configuring UEFI boot entries during build
-      - linux-firmware       # Provides essential device drivers for the guest kernel
-      - openssh-server
-      - NetworkManager
-      - tar
+  - packages:
+    - cronie
+    - cronie-noanacron
+    - curl
+    - glibc-langpack-en
+    - glibc-locale-source
+    - hostname
+    - initscripts
+    - iproute
+    - openssh-clients
+    - passwd
+    - policycoreutils
+    - rootfiles
+    - rsyslog
+    - sudo
+    - vim-minimal
+    action: install
 
-      # --- K8s Networking Dependencies ---
-      - iptables # Needed by kube-proxy to route internal cluster pod traffic
-      - iproute # Grants the node low-level network management binaries (ip, bridge)
-      - conntrack-tools # Essential for tracking network state connections across pods
-      - socat # Required by the kubelet agent to forward traffic ports (kubectl port-forward)
+  - packages:
+    - dhclient
+    action: install
+    releases: # dhclient is not available in 10
+    - 8
+    - 9
 
-      # --- Diagnostic & Troubleshooting Tools ---
-      - curl # Used to fetch configurations, manifests, and pull binaries
-      - wget # Standard alternate retrieval tool
-      - iputils # Includes the 'ping' command for debugging pod-to-pod links
-      - python3-libdnf
-  repositories: []
-  
+  - packages:
+    - network-scripts
+    action: install
+    types:
+    - container
+    releases:
+    - 8
+
+  - packages:
+    - NetworkManager
+    action: install
+    types:
+    - vm
+    variants:
+    - default
+
+  - packages:
+    - cloud-init
+    - NetworkManager
+    action: install
+    variants:
+    - cloud
+
+  - packages:
+    - NetworkManager
+    action: install
+    types:
+    - container
+    releases:
+    - 9
+    - 10
+    variants:
+    - default
+
+  - packages:
+    - cloud-utils-growpart
+    action: install
+    types:
+    - vm
+    variants:
+    - cloud
+
+  - packages:
+    - shim
+    action: install
+    types:
+    - vm
+
+  - packages:
+    - kernel
+    action: install
+    types:
+    - vm
+
+  - packages:
+    - grub2-efi-x64
+    action: install
+    types:
+    - vm
+    architectures:
+    - x86_64
+
+  - packages:
+    - grub2-efi-aarch64
+    action: install
+    types:
+    - vm
+    architectures:
+    - aaarch64
+
 actions:
-  - trigger: post-packages
-    action: |-
-      #!/bin/bash
-      # Generate GRUB config
-      grub2-mkconfig -o /boot/grub2/grub.cfg
-      
-      # Ensure default boot entry (set to 0 for first entry)
-      sed -i 's/^#GRUB_DEFAULT=.*/GRUB_DEFAULT=0/' /etc/default/grub
-      
-      # Install GRUB for UEFI
-      grub2-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=rocky
-      
-      # Regenerate config with new defaults
-      grub2-mkconfig -o /boot/grub2/grub.cfg
-      
-      # Enable services
-      systemctl enable NetworkManager.service
-      systemctl enable sshd.service
-      systemctl enable incus-agent.service
-      systemctl enable systemd-modules-load.service
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+    # Make sure we have our template targets
+    touch /etc/hosts
+    touch /etc/hostname
 
-mappings:
-  architecture_map: centos
+- trigger: post-unpack
+  action: |-
+    #!/bin/sh
+    # Generate machine-id in order for the kernel stuff to be configured properly
+    systemd-machine-id-setup
+  types:
+  - vm
+
+- trigger: post-packages
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Disable SELinux
+    mkdir -p /selinux
+    echo 0 > /selinux/enforce
+
+    # Disable loginuid in PAM stack
+    sed -i '/^session.*pam_loginuid.so/s/^session/# session/' /etc/pam.d/*
+
+    # Set default locale
+    localedef -i en_US -f UTF-8 en_US.UTF-8
+    echo 'LANG=en_US.utf8' > /etc/locale.conf
+
+    # Disable first boot wizard
+    systemctl mask systemd-firstboot.service
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Regenerate initramfs
+    kver=$(ls /boot/initramfs-*.img | sed -r 's#.*initramfs-(.+)\.img#\1#')
+    dracut --kver "${kver}" -f
+
+    target="$(readlink -f /etc/grub2-efi.cfg)"
+    grub2-mkconfig -o "${target}"
+
+    sed -i "s#root=[^ ]*#root=${DISTROBUILDER_ROOT_UUID}#g" "${target}"
+  types:
+  - vm
+  releases:
+  - 8
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+    kver=$(ls /boot/initramfs-*.img | sed -r 's#.*initramfs-(.+)\.img#\1#')
+    target=/boot/efi/EFI/rocky/grub.cfg
+    # Create grub.cfg file
+    grub2-mkconfig -o "${target}"
+    sed -i "s#root=[^ ]*#root=${DISTROBUILDER_ROOT_UUID}#g" "${target}"
+
+    # Update the default kernel command line, loop0p2 is still present there,
+    # which will be added by postinst scriptlets when installing or reinstalling
+    # a kernel. This fixes the rootfs mount on subsequent boots after upgrading
+    # the kernel.
+    if [ -f /etc/kernel/cmdline ]; then
+      sed -i "s#root=[^ ]*#root=${DISTROBUILDER_ROOT_UUID}#g" /etc/kernel/cmdline
+    fi
+
+    # Update files in /boot/loader/entries/. `grubby` needs to be run after
+    # `grub2-mkconfig` as the latter overwrites files in /boot/loader/entries/.
+    grubby --update-kernel=/boot/vmlinuz-${kver} --args="root=${DISTROBUILDER_ROOT_UUID} ro"
+
+    # Regenerate initramfs
+    dracut --kver "${kver}" -f
+  types:
+  - vm
+  releases:
+  - 9
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    # Track down the kernel
+    kver=$(basename /boot/initramfs-*.img | sed -r 's#initramfs-(.+)\.img#\1#' | head -n1)
+    if [ -z "$kver" ]; then
+      echo "No initramfs found in /boot!" >&2
+      exit 1
+    fi
+
+    kernel_path=$(find /boot -name "vmlinuz-${kver}" || true)
+    if [ -z "$kernel_path" ]; then
+      echo "Kernel image /boot/vmlinuz-${kver} not found!" >&2
+      ls -l /boot >&2
+      exit 1
+    fi
+
+    # Track down the root disk
+    root_dev=$(df / | tail -n1 | awk '{print $1}')
+    if [ -b "$root_dev" ]; then
+      root_uuid=$(blkid -s UUID -o value "$root_dev")
+      if [ -z "$root_uuid" ]; then
+        echo "Failed to get UUID for $root_dev" >&2
+        exit 1
+      fi
+    else
+      echo "Error: Root device $root_dev not found!" >&2
+      exit 1
+    fi
+
+    # Re-generate the initrd
+    . /etc/os-release
+    GRUB_ENTRY_NAME="${NAME} ${VERSION} ${kver}"
+    dracut --kver "${kver}" -f --no-hostonly --add-drivers "virtio_scsi virtio_console sd_mod ext4 virtio_blk virtio_pci scsi_mod" --install "blkid"
+
+
+    # Track down the EFI partition
+    disk_dev=$(lsblk -no pkname "$root_dev" | head -n1)
+    if [ -z "$disk_dev" ]; then
+      echo "Failed to find disk device for $root_dev" >&2
+      exit 1
+    fi
+    disk_dev="/dev/$disk_dev"
+
+    efi_part="${disk_dev}p1"
+    if [ ! -b "$efi_part" ]; then
+      echo "EFI partition $efi_part not found!" >&2
+      exit 1
+    fi
+
+    # Generate the grub configuration
+    mkdir -p /mnt/efi
+    mount "$efi_part" /mnt/efi
+
+    mkdir -p /mnt/efi/EFI/rocky
+    cat > "/mnt/efi/EFI/rocky/grub.cfg" <<EOF
+    set timeout=5
+    set default=0
+
+    menuentry '${GRUB_ENTRY_NAME}' {
+        set root=(hd0,gpt2)
+        linux /boot/vmlinuz-${kver} root=UUID=${root_uuid} ro console=tty1 console=ttyS0
+        initrd /boot/initramfs-${kver}.img
+    }
+
+    menuentry 'UEFI Firmware Settings' {
+        fwsetup
+    }
+    EOF
+
+    umount /mnt/efi
+    mkdir -p /boot/grub2
+    touch /boot/grub2/grubenv
+  types:
+  - vm
+  releases:
+  - 10
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    systemctl enable NetworkManager.service
+  types:
+  - vm
+  variants:
+  - default
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    mkdir -p /etc/NetworkManager/conf.d/
+    printf "[main]\ndhcp=internal\n" > /etc/NetworkManager/conf.d/dhcp-client.conf
+
+    systemctl enable NetworkManager.service
+  types:
+  - container
+  variants:
+  - default
+  releases:
+  - 10
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    mkdir -p /etc/NetworkManager/conf.d/
+    printf "[main]\ndhcp=dhclient\n" > /etc/NetworkManager/conf.d/dhcp-client.conf
+
+    systemctl enable NetworkManager.service
+  types:
+  - container
+  variants:
+  - default
+  releases:
+  - 9
+
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eux
+
+    systemctl enable network
+  types:
+  - container
+  variants:
+  - default
+  releases:
+  - 8
+
+- trigger: post-files #apparently this changes password
+  action: |-
+    #!/bin/sh
+    set -eux
+    # Sets the default root password to 'kubeadmin123'
+    echo "root:kubeadmin123" | chpasswd
+  types:
+    - vm
